-- Non-destructive upgrade: add SSLCOMMERZ reconciliation without changing existing rows.
-- Run as SMART_TRAFFIC in SQL Developer. Safe to re-run.
SET SQLBLANKLINES ON

BEGIN
    DECLARE
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
        FROM user_tables
        WHERE table_name = 'SSL_GATEWAY_ATTEMPT';

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE q'[
                CREATE TABLE SSL_GATEWAY_ATTEMPT (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    Tran_id VARCHAR2(30) NOT NULL,
                    Vehicle_owner_id NUMBER NOT NULL,
                    Notice_id NUMBER NOT NULL,
                    Expected_amount NUMBER(10,2) NOT NULL,
                    Currency VARCHAR2(3) DEFAULT 'BDT' NOT NULL,
                    Status VARCHAR2(20) NOT NULL,
                    Session_key VARCHAR2(50),
                    Val_id VARCHAR2(50),
                    Payment_id NUMBER,
                    Created_at DATE DEFAULT SYSDATE NOT NULL,
                    Updated_at DATE DEFAULT SYSDATE NOT NULL,
                    CONSTRAINT PK_SSL_GATEWAY_ATTEMPT PRIMARY KEY (ID),
                    CONSTRAINT UK_SSL_GATEWAY_TRAN UNIQUE (Tran_id),
                    CONSTRAINT UK_SSL_GATEWAY_VAL UNIQUE (Val_id),
                    CONSTRAINT FK_SSL_GW_OWNER FOREIGN KEY (Vehicle_owner_id) REFERENCES VEHICLE_OWNER(ID),
                    CONSTRAINT FK_SSL_GW_NOTICE FOREIGN KEY (Notice_id) REFERENCES NOTICE(ID),
                    CONSTRAINT FK_SSL_GW_PAYMENT FOREIGN KEY (Payment_id) REFERENCES PAYMENT(ID),
                    CONSTRAINT CK_SSL_GW_STATUS CHECK (Status IN ('Initiated', 'Failed', 'Cancelled', 'Successful')),
                    CONSTRAINT CK_SSL_GW_CURRENCY CHECK (Currency = 'BDT'),
                    CONSTRAINT CK_SSL_GW_AMOUNT CHECK (Expected_amount > 0)
                )
            ]';
        END IF;
    END;
END;
/
